---
# tasks file for onion relay

- name: Add torproject gpg key
  apt_key:
    data: "{{ lookup('file', 'torproject.asc') }}"
    id: A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
    state: present

- name: Add torproject repository
  become: yes
  apt_repository:
    repo: 'deb https://deb.torproject.org/torproject.org {{ ansible_lsb.codename }} main'
    state: present
    update_cache: yes

- name: Install tor and Unbound
  apt: name={{ item }} state=present
  with_items:
    - tor
    - deb.torproject.org-keyring
    - unbound
    - vnstat
    - vnstati

- name: Make resolv.conf mutable
  file:
    path: /etc/resolv.conf
    attributes: e

- name: Set Tor and Unbound configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - {
      src: "torrc.j2",
      dest: "/etc/tor/torrc"
      }
    - {
      src: "resolv.conf.j2",
      dest: "/etc/resolv.conf"
      }

- name: Set vnstat script
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - {
      src: "vnstati.sh.j2",
      dest: "/usr/local/bin/vnstati.sh"
      }

- name: Set vnstat cron
  file:
    src: "/usr/local/bin/vnstati.sh"
    dest: "/etc/cron.hourly/vnstati"
    state: link

- name: Make resolv.conf immutable
  file:
    path: /etc/resolv.conf
    attributes: ie

- name: Restart tor
  become: yes
  service: name=tor@default state=restarted
